# vim: set filetype=dockerfile
FROM localhost/local-ai-chat-lightspeed-stack:latest

USER root

ADD ./llama-stack /app-root/llama-stack

RUN python3.12 -m ensurepip

RUN cd /app-root/llama-stack && python3.12 -m pip install --editable .

RUN cd /app-root/ && python3.12 -m pip install .

RUN microdnf install -y patch

# Patch created based on https://github.com/llamastack/llama-stack/pull/3957
COPY  llama-stack-make-tool-call-args-fully-recursive.patch /tmp/
RUN cat /tmp/llama-stack-make-tool-call-args-fully-recursive.patch \
  | patch -p1 -d "$(dirname "$(dirname "$(python3.12 -c "import llama_stack; print(llama_stack.__file__)")")")"

COPY migrate.py /app/migrate.py
ENTRYPOINT ["/bin/sh", "-c", "python3.12 /app/migrate.py && python3.12 src/lightspeed_stack.py"]

USER 1001

EXPOSE 8080

