FROM quay.io/redhat-user-workloads/assisted-installer-tenant/assisted-chat-rag:latest AS rag
# vim: set filetype=dockerfile
FROM localhost/local-ai-chat-lightspeed-stack:latest

USER root

ADD ./llama-stack /app-root/llama-stack

RUN python3.12 -m ensurepip

RUN cd /app-root/llama-stack && python3.12 -m pip install --editable .

RUN cd /app-root/ && python3.12 -m pip install .

COPY --from=rag /app/all-mpnet-base-v2/ /app-root/all-mpnet-base-v2/
COPY --from=rag /app/llama_stack_vector_db/ /app-root/llama_stack_vector_db/
COPY migrate.py /app/migrate.py
COPY --chmod=755 --chown=1001:1001 scripts/entrypoint.sh entrypoint.sh
ENTRYPOINT ["entrypoint.sh"]

USER 1001

EXPOSE 8080

