# vim: set filetype=dockerfile
# This is the digest of quay.io/lightspeed-core/lightspeed-stack:0.1.1
FROM quay.io/lightspeed-core/lightspeed-stack@sha256:c4c795e66cb3f27715f991895e2cd8e45c714c3f6ebdca066e8ab13a231ba3c0

RUN python3 -m ensurepip --default-pip && pip install --upgrade pip

RUN python3 -m pip install pyyaml pyaml litellm sqlalchemy mcp psycopg2-binary

USER 1001

EXPOSE 8080
