# vim: set filetype=dockerfile
FROM registry.access.redhat.com/ubi9/python-312-minimal

RUN python3 -m ensurepip --default-pip && pip install --upgrade pip
RUN python3 -m pip install pyyaml pyaml litellm sqlalchemy mcp

EXPOSE 8080
