version: 2
image_name: starter
storage:
  backends:
    kv_default:
      type: kv_sqlite
      db_path: ${env.SQLITE_STORE_DIR:=/tmp/.llama/distributions/starter}/kvstore.db
    sql_default:
      type: sql_postgres
      host: ${env.POSTGRES_HOST:=localhost}
      port: ${env.POSTGRES_PORT:=5432}
      db: ${env.POSTGRES_DB:=assisted-chat}
      user: ${env.POSTGRES_USER:=assisted-chat}
      password: ${env.POSTGRES_PASSWORD:=assisted-chat}
  stores:
    metadata:
      backend: kv_default
      namespace: registry
    inference:
      backend: sql_default
      table_name: inference_store
    conversations:
      backend: sql_default
      table_name: openai_conversations
apis:
- agents
- datasetio
- eval
- files
- inference
- safety
- scoring
- tool_runtime
- vector_io
providers:
  inference:
  - config:
      project: ${env.VERTEX_AI_PROJECT}
    provider_id: gemini
    provider_type: remote::vertexai
  - config: {}
    provider_id: sentence-transformers
    provider_type: inline::sentence-transformers
  vector_io:
  - config:
      persistence:
        backend: kv_default
        namespace: ocp-assisted-installer-4-19
    provider_id: ocp-assisted-installer-4-19
    provider_type: inline::faiss
  files:
  - config:
      storage_dir: /tmp/llama-stack-files
      metadata_store:
        backend: sql_default
        table_name: files_metadata
    provider_id: localfs
    provider_type: inline::localfs
  safety: []
  agents:
  - provider_id: meta-reference
    provider_type: inline::meta-reference
    config:
      persistence:
        agent_state:
          backend: kv_default
          namespace: agents
        responses:
          backend: sql_default
          table_name: agent_responses
  eval: []
  datasetio: []
  scoring:
  - provider_id: basic
    provider_type: inline::basic
    config: {}
  - provider_id: llm-as-judge
    provider_type: inline::llm-as-judge
    config: {}
  tool_runtime:
  - provider_id: model-context-protocol
    provider_type: remote::model-context-protocol
    config: {}
  - provider_id: rag-runtime
    provider_type: inline::rag-runtime
    config: {}
models:
- metadata:
    embedding_dimension: 768
  model_id: sentence-transformers/all-mpnet-base-v2
  provider_id: sentence-transformers
  provider_model_id: /app-root/all-mpnet-base-v2
  model_type: embedding
shields: []
vector_dbs:
  - vector_db_id: ocp-assisted-installer-4-19
    embedding_model: sentence-transformers/all-mpnet-base-v2
    embedding_dimension: 768
    provider_id: ocp-assisted-installer-4-19
    provider_vector_db_id: ocp-assisted-installer-4-19
datasets: []
scoring_fns: []
benchmarks: []
tool_groups:
- toolgroup_id: mcp::assisted
  provider_id: model-context-protocol
  mcp_endpoint:
    uri: "http://assisted-service-mcp:8000/mcp"
- toolgroup_id: builtin::rag
  provider_id: rag-runtime
server:
  port: 8321
